require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'app/models/ckeditor/**'
    - 'Gemfile'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Style/Semicolon:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%i': '()'

Lint/RedundantSplatExpansion:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true
 
Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true
 
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
