AllCops:
  TargetRubyVersion: 2.3
  DisplayStyleGuide: true
  DisplayCopNames: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - '**/bin/**'
    - '**/db/schema.rb'
    - '**/db/migrate/**'
    - '**/app/models/ckeditor/**'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false