production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/discursus
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/discursus

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/dsc_test
    