production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/discursus
    read_timeout: 20
    open_timeout: 10
  auto_commit_after_request: false
  auto_commit_after_delete_request: true

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/discursus

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/dsc_test
    